### ISSUE TITLE
Link para o Discord quebrado

### ISSUE THREAD

**Issue by lucasskluser** [blumenaujs/site#2]
Olá!

O link para o servidor no Discord expirou.

![image](https://user-images.githubusercontent.com/28795323/73556191-b0e16500-442d-11ea-8cfa-2ebc9828cadd.png)

**Comment by vmarcosp** [comment]
Olá @lukesamk obrigado por nós avisar, já estou verificando isso :)

**Comment by vmarcosp** [comment]
@lukesamk resolvido :)
Caso queira entrar no nosso discord podes usar o link abaixo:
[https://discord.gg/qccyVyK](https://discord.gg/qccyVyK)
tks :crossed_fingers:
